apiVersion: v1
kind: Service
metadata:
  name: pxc-cluster
  namespace: mobility-asia
  labels:
    unit: pxc-cluster
spec:
  type: NodePort
  ports:
    - port: 3306
      name: pxc-mysql
  selector:
    unit: pxc-cluster